name: todoist-cli
base: core18 # the base snap is the execution environment for this snap
version: '0.13.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Todoist CLI Client
description: |
  Todoist CLI Client, written in Golang.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
#architectures:
#- build-on: amd64
#run-on: amd64
license: MIT

parts:
  todoist-cli:
    plugin: go
    source: .
    go-importpath: github.com/sachaos/todoist
    build-packages:
      - git
      - build-essential

apps:
  todoist-cli:
    command: todoist
